In [1]:
import numpy as np
#Q1 to make array of (10,1) using numpy

a=np.random.rand(10,1)
print(a)
print('--'*50)




[[0.31495338]
 [0.81654144]
 [0.17856772]
 [0.5062897 ]
 [0.28536478]
 [0.65346855]
 [0.49113057]
 [0.57528572]
 [0.89757191]
 [0.01417717]]
----------------------------------------------------------------------------------------------------


In [2]:
#Q2 To make array of (20,1) and find variance and standard deviation
a=np.random.random((20,1))
print(a)
print('--'*50)
#standard deviation
print(np.std(a))
print('--'*50)
#variance
print(np.std(a)**2)




[[0.62082329]
 [0.61834892]
 [0.04522422]
 [0.63436665]
 [0.46162072]
 [0.12972647]
 [0.71347834]
 [0.94696975]
 [0.79913367]
 [0.18592689]
 [0.79785857]
 [0.06740308]
 [0.88696705]
 [0.42104168]
 [0.98582684]
 [0.92105488]
 [0.6346355 ]
 [0.67621693]
 [0.35462388]
 [0.06922276]]
----------------------------------------------------------------------------------------------------
0.30655161435582895
----------------------------------------------------------------------------------------------------
0.09397389226416487


In [3]:
#Q3 Matrix multiplication and sum
a=np.random.rand(10,20)
b=np.random.rand(20,25)
m=np.matmul(a,b)
print('--'*70)
print(m)
print('--'*70)
print(m.shape)
print('--'*70)
print(np.sum(m))



--------------------------------------------------------------------------------------------------------------------------------------------
[[6.22751469 5.79897588 5.07660241 5.17476654 5.78183487 5.53306563
  6.51786482 6.32876339 6.23174657 4.69385233 4.88408777 5.29536677
  6.60205082 6.50475847 5.2901663  5.72324436 4.92506139 4.86473324
  5.02464987 5.55842093 4.9969736  5.87215234 5.3401797  6.06712149
  5.25143574]
 [5.82622462 4.97776451 4.39069107 4.91283809 4.85171507 3.93426532
  5.99885073 4.815956   5.32937212 4.01466685 4.47460187 4.1681774
  4.74350148 4.74659051 5.03232186 5.89110026 3.50657815 4.18786467
  3.51519351 5.8696152  3.59130219 5.19570411 4.82106294 4.73053872
  4.7087258 ]
 [6.98107779 6.70547717 4.39965698 6.36236348 5.97927392 7.11004691
  8.08851339 6.40603943 7.26916093 5.6331595  6.60828533 5.68137655
  6.87134966 7.38704795 6.42840247 7.26170621 6.08728014 6.14541797
  5.93489649 6.9061307  6.17582145 6.93850866 6.37315334 7.32082651
  6.61444405]
 [

In [8]:

#Q4 to make an array and a function as (1/1+exp(-x))
a= np.random.rand(10,1)
print(a)
print('--'*50)
def f(x):
    return (1 / (1 + np.exp(-x)))

r = np.apply_along_axis(f, 0, a)
print(r)

[[0.00584088]
 [0.64755579]
 [0.145702  ]
 [0.41029566]
 [0.88143871]
 [0.33090988]
 [0.76665827]
 [0.04330287]
 [0.97513048]
 [0.58375298]]
----------------------------------------------------------------------------------------------------
[[0.50146021]
 [0.65645945]
 [0.5363612 ]
 [0.60115877]
 [0.70712027]
 [0.58198075]
 [0.68279757]
 [0.51082403]
 [0.72614093]
 [0.64193051]]
